var hierarchy =
[
    [ "tomtom::core::transport::BLEDeviceDetails", "structtomtom_1_1core_1_1transport_1_1BLEDeviceDetails.html", null ],
    [ "tomtom::core::protocol::runtime::ByteView", "structtomtom_1_1core_1_1protocol_1_1runtime_1_1ByteView.html", null ],
    [ "tomtom::cli::CliContext", "structtomtom_1_1cli_1_1CliContext.html", null ],
    [ "tomtom::core::protocol::definitions::CloseFileTxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1CloseFileTxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::DeleteFileTxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1DeleteFileTxPayload.html", null ],
    [ "tomtom::core::transport::DeviceConnection", "classtomtom_1_1core_1_1transport_1_1DeviceConnection.html", [
      [ "tomtom::core::transport::USBDeviceConnection", "classtomtom_1_1core_1_1transport_1_1USBDeviceConnection.html", null ]
    ] ],
    [ "tomtom::core::transport::DeviceConnectionFactory", "classtomtom_1_1core_1_1transport_1_1DeviceConnectionFactory.html", null ],
    [ "tomtom::core::transport::DeviceInfo", "structtomtom_1_1core_1_1transport_1_1DeviceInfo.html", null ],
    [ "tomtom::core::commands::FileEntry", "structtomtom_1_1core_1_1commands_1_1FileEntry.html", null ],
    [ "tomtom::core::protocol::definitions::FileOperationResponse", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1FileOperationResponse.html", [
      [ "tomtom::core::protocol::definitions::CloseFileRxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1CloseFileRxPayload.html", null ],
      [ "tomtom::core::protocol::definitions::DeleteFileRxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1DeleteFileRxPayload.html", null ],
      [ "tomtom::core::protocol::definitions::OpenFileReadRxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1OpenFileReadRxPayload.html", null ],
      [ "tomtom::core::protocol::definitions::OpenFileWriteRxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1OpenFileWriteRxPayload.html", null ]
    ] ],
    [ "tomtom::core::commands::FileOperations", "classtomtom_1_1core_1_1commands_1_1FileOperations.html", null ],
    [ "tomtom::core::protocol::definitions::FileSizeResponse", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1FileSizeResponse.html", [
      [ "tomtom::core::protocol::definitions::GetFileSizeRxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1GetFileSizeRxPayload.html", null ]
    ] ],
    [ "tomtom::core::protocol::definitions::FindFirstFileTxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1FindFirstFileTxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::FindNextFileTxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1FindNextFileTxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::FindResponse", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1FindResponse.html", [
      [ "tomtom::core::protocol::definitions::FindFirstFileRxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1FindFirstFileRxPayload.html", null ],
      [ "tomtom::core::protocol::definitions::FindNextFileRxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1FindNextFileRxPayload.html", null ]
    ] ],
    [ "tomtom::core::protocol::definitions::FormatWatchRxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1FormatWatchRxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::FormatWatchTxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1FormatWatchTxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::GetBleVersionRxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1GetBleVersionRxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::GetBleVersionTxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1GetBleVersionTxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::GetFileSizeTxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1GetFileSizeTxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::GetFirmwareVersionRxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1GetFirmwareVersionRxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::GetFirmwareVersionTxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1GetFirmwareVersionTxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::GetProductIdRxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1GetProductIdRxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::GetProductIdTxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1GetProductIdTxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::GetWatchTimeRxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1GetWatchTimeRxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::GetWatchTimeTxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1GetWatchTimeTxPayload.html", null ],
    [ "tomtom::core::transport::USBDeviceConnection::Impl", "classtomtom_1_1core_1_1transport_1_1USBDeviceConnection_1_1Impl.html", null ],
    [ "tomtom::core::commands::KernelOperations", "classtomtom_1_1core_1_1commands_1_1KernelOperations.html", null ],
    [ "tomtom::core::utils::Logger", "classtomtom_1_1core_1_1utils_1_1Logger.html", null ],
    [ "tomtom::core::protocol::definitions::OpenFileReadTxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1OpenFileReadTxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::OpenFileWriteTxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1OpenFileWriteTxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::Packet< PacketPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1Packet.html", null ],
    [ "tomtom::core::protocol::runtime::PacketHandler", "classtomtom_1_1core_1_1protocol_1_1runtime_1_1PacketHandler.html", null ],
    [ "tomtom::core::protocol::definitions::PacketHeader", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PacketHeader.html", null ],
    [ "tomtom::core::protocol::runtime::PacketResponse< PacketType >", "structtomtom_1_1core_1_1protocol_1_1runtime_1_1PacketResponse.html", null ],
    [ "tomtom::core::protocol::runtime::PacketValidator", "classtomtom_1_1core_1_1protocol_1_1runtime_1_1PacketValidator.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< PacketPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< CloseFileRxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01CloseFileRxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< CloseFileTxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01CloseFileTxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< DeleteFileRxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01DeleteFileRxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< DeleteFileTxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01DeleteFileTxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< FindFirstFileRxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01FindFirstFileRxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< FindFirstFileTxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01FindFirstFileTxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< FindNextFileRxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01FindNextFileRxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< FindNextFileTxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01FindNextFileTxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< FormatWatchRxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01FormatWatchRxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< FormatWatchTxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01FormatWatchTxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< GetBleVersionRxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01GetBleVersionRxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< GetBleVersionTxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01GetBleVersionTxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< GetFileSizeRxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01GetFileSizeRxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< GetFileSizeTxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01GetFileSizeTxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< GetFirmwareVersionRxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01GetFirmwareVersionRxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< GetFirmwareVersionTxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01GetFirmwareVersionTxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< GetProductIdRxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01GetProductIdRxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< GetProductIdTxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01GetProductIdTxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< GetWatchTimeRxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01GetWatchTimeRxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< GetWatchTimeTxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01GetWatchTimeTxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< OpenFileReadRxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01OpenFileReadRxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< OpenFileReadTxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01OpenFileReadTxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< OpenFileWriteRxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01OpenFileWriteRxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< OpenFileWriteTxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01OpenFileWriteTxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< ReadFileDataRxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01ReadFileDataRxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< ReadFileDataTxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01ReadFileDataTxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< ResetDeviceTxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01ResetDeviceTxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< ResetGpsRxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01ResetGpsRxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< ResetGpsTxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01ResetGpsTxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< WriteFileDataRxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01WriteFileDataRxPayload_01_4.html", null ],
    [ "tomtom::core::protocol::definitions::PayloadTraits< WriteFileDataTxPayload >", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1PayloadTraits_3_01WriteFileDataTxPayload_01_4.html", null ],
    [ "tomtom::cli::ProgressIndicator", "classtomtom_1_1cli_1_1ProgressIndicator.html", null ],
    [ "tomtom::core::protocol::definitions::ReadFileDataRxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1ReadFileDataRxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::ReadFileDataTxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1ReadFileDataTxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::ResetDeviceTxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1ResetDeviceTxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::ResetGpsRxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1ResetGpsRxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::ResetGpsTxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1ResetGpsTxPayload.html", null ],
    [ "std::runtime_error", null, [
      [ "tomtom::core::protocol::runtime::CodecError", "classtomtom_1_1core_1_1protocol_1_1runtime_1_1CodecError.html", [
        [ "tomtom::core::protocol::runtime::ConnectionError", "classtomtom_1_1core_1_1protocol_1_1runtime_1_1ConnectionError.html", null ],
        [ "tomtom::core::protocol::runtime::MalformedPacketError", "classtomtom_1_1core_1_1protocol_1_1runtime_1_1MalformedPacketError.html", null ],
        [ "tomtom::core::protocol::runtime::TimeoutError", "classtomtom_1_1core_1_1protocol_1_1runtime_1_1TimeoutError.html", null ],
        [ "tomtom::core::protocol::runtime::UnexpectedPacketError", "classtomtom_1_1core_1_1protocol_1_1runtime_1_1UnexpectedPacketError.html", null ]
      ] ]
    ] ],
    [ "tomtom::core::transport::USBDeviceConnectionImpl", "structtomtom_1_1core_1_1transport_1_1USBDeviceConnectionImpl.html", null ],
    [ "tomtom::core::transport::USBDeviceDetails", "structtomtom_1_1core_1_1transport_1_1USBDeviceDetails.html", null ],
    [ "tomtom::core::Watch", "classtomtom_1_1core_1_1Watch.html", null ],
    [ "tomtom::core::protocol::definitions::WriteFileDataRxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1WriteFileDataRxPayload.html", null ],
    [ "tomtom::core::protocol::definitions::WriteFileDataTxPayload", "structtomtom_1_1core_1_1protocol_1_1definitions_1_1WriteFileDataTxPayload.html", null ]
];